name: Retrain Model

on:
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch new feedback data
        run: |
          python mongodb.py
        env:
          MONGO_CONN_STR: ${{ secrets.MONGO_CONN_STR }}

      - name: Retrain model
        run: |
          python retrain.py
        env:
          MONGO_CONN_STR: ${{ secrets.MONGO_CONN_STR }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add pkl_files/*.pkl
          git add training_data/all_data_bouldering.csv
          git add training_data/all_data_sport.csv
          git commit -m 'Retrain model with new data and update all data'
          git push https://github-actions:${{ secrets.GH_PAT }}@github.com/Tetleysteabags/climbing_grade_predictions.git HEAD:main
